Table implementation
ashotvdovychenko/js-interactive-table pull request #1
Opened 2023-10-18 22:19 UTC by ashotvdovychenko

2023-10-18 22:22 UTC, Pagendera approved these changes

2023-10-19 16:03 UTC, Pagendera requested changes

2023-10-19 16:03 UTC, Pagendera commented on scripts/form.js
> +        additionalValidators.forEach(additionalValidator => additionalValidator(this.#controlRef))
Please, don't forget about semicolon, recheck all files and fix it

2023-10-19 16:15 UTC, Pagendera requested changes

2023-10-19 16:15 UTC, Pagendera commented on scripts/form.js
> +            const isBackspace = keyCode === 8;
Backspace is not working

2023-10-19 16:22 UTC, Pagendera requested changes

2023-10-19 16:22 UTC, Pagendera commented on scripts/form.js
> +    #getPhoneMaskWithRemovedNumber(value, initialMask) {
Method is not working

2023-10-19 19:53 UTC, ashotvdovychenko commented on scripts/form.js
> +        additionalValidators.forEach(additionalValidator => additionalValidator(this.#controlRef))
Fixed

2023-10-19 19:54 UTC, ashotvdovychenko commented on scripts/form.js
> +    #getPhoneMaskWithRemovedNumber(value, initialMask) {
Fixed

2023-10-19 19:54 UTC, neodavis approved these changes

2023-10-19 19:54 UTC, Pagendera approved these changes

2023-10-19 19:54 UTC, merged